Fede.step
Appsilon/shiny.semantic pull request #350
Opened 2021-02-03 23:22 UTC by federiva

Implementing Step - Work in Progress

See [here](https://fomantic-ui.com/elements/step.html) for reference

**DoD**

- [ ] Major project work has a corresponding task. If there’s no task for what you are doing, create it. Each task needs to be well defined and described.

- [ ] Change has been tested (manually or with automated tests), everything runs correctly and works as expected. No existing functionality is broken.

- [ ] No new error or warning messages are introduced.

- [ ] All interaction with a semantic functions, examples and docs are written from the perspective of the person using or receiving it. They are understandable and helpful to this person.

- [ ] If the change affects code or repo sctructure, README, documentation and code comments should be updated. 

- [ ] All code has been peer-reviewed before merging into any main branch.

- [ ] All changes have been merged into the main branch we use for development (develop).

- [ ] Continuous integration checks (linter, unit tests) are configured and passed.

- [ ] Unit tests added for all new or changed logic.

- [ ] All task requirements satisfied. The reviewer is responsible to verify each aspect of the task.

- [ ] Any added or touched code follows our style-guide.

2021-02-03 23:23 UTC, federiva commented
For the purpose of testing you can try the example in the steps function documentation

2021-02-12 10:00 UTC, dokato requested changes
Looks really good, great job 👍 See some minor comments below.

Still TODO:
- add example to `example/app.R` (and ask DB for deploy to our demo server)
- add simple unit tests

2021-03-02 17:38 UTC, federiva commented on R/step.R
> +#'  hr(),
done

2021-03-02 17:56 UTC, federiva commented on R/step.R
> +    id <- ifelse(
done

2021-03-02 17:56 UTC, federiva commented on R/step.R
> +    step_class <- ifelse(
done

2021-03-02 17:56 UTC, federiva commented on R/step.R
> +}
done

2021-03-08 12:58 UTC, dokato approved these changes
LGTM, great job @federiva !

2021-03-08 12:58 UTC, merged